<?php
$pageTitle = "Upload IV Sweep";
require "../config/header.php";
?>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-header bg-primary text-white">
                    <h5 class="mb-0"><i class="bi bi-file-earmark-arrow-up"></i> Upload IV Sequence File</h5>
                </div>
                <div class="card-body">
                    <p class="text-muted small">
                        Select the <strong>.SEQ</strong> file generated by the Solar Simulator. <br>
                        The system will automatically detect the Cell ID, Operator, and Sweep Directions.
                    </p>

                    <form action="process_iv.php" method="POST" enctype="multipart/form-data" id="uploadForm">
                        <div class="mb-4">
                            <label for="iv_file" class="form-label fw-bold">Select File</label>
                            <input class="form-control form-control-lg" type="file" id="iv_file" name="iv_file" accept=".SEQ,.txt" required>
                        </div>

                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary btn-lg" id="submitBtn">
                                <span id="btnText">Parse & Preview Data</span>
                                <span id="btnSpinner" class="spinner-border spinner-border-sm d-none" role="status"></span>
                            </button>
                        </div>
                    </form>
                </div>
                <div class="card-footer bg-light">
                    <div class="d-flex justify-content-between small">
                        <span>Format: <strong>.SEQ</strong></span>
                        <a href="iv_test_list.php" class="text-decoration-none">Cancel</a>
                    </div>
                </div>
            </div>

            <?php if (isset($_GET['error'])): ?>
                <div class="alert alert-danger mt-3">
                    <?php
                    if ($_GET['error'] == 'session_expired') echo "Upload session expired. Please try again.";
                    else echo "An error occurred during upload.";
                    ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>

<script>
    // Visual feedback so the user knows the file is being processed
    document.getElementById('uploadForm').addEventListener('submit', function() {
        const btn = document.getElementById('submitBtn');
        const text = document.getElementById('btnText');
        const spinner = document.getElementById('btnSpinner');

        btn.disabled = true;
        text.innerText = "Processing...";
        spinner.classList.remove('d-none');
    });
</script>

<?php require "../config/footer.php"; ?>